server:
  port: 8002
spring:
  application:
    name: dubbo-demo-provider

dubbo:
  application:
    name: ${spring.application.name}
    # 可选值 interface、instance、all，默认是 all，即接口级地址、应用级地址都注册
    register-mode: instance
  protocol:
    name: dubbo
    port: 18002
  registry:
    address: nacos://localhost:8848
    version: 1.0.0
#  provider:
#    group: dubbo-demo