server:
  port: 8002

spring:
  application:
    name: spring-cloud-demo-consumer
  cloud:
    # 使用 Nacos 作为注册中心
    nacos:
      discovery:
        server-addr: localhost:8848
        group: springcloud
    # 使用 Sentinel 进行流量控制
    sentinel:
      eager: true      # 取消控制台懒加载
      transport:
        port: 8732     # 上报给控制台的端口
        dashboard: 127.0.0.1:8080        # 控制台地址
      datasource:
        nacos-degrade:
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: public
            username: nacos
            password: nacos
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP        # 需要与 Sentinel 控制台的 GroupId 一致
            data-type: json
            rule-type: degrade
        nacos-flow:
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: public
            username: nacos
            password: nacos
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP        # 需要与 Sentinel 控制台的 GroupId 一致
            data-type: json
            rule-type: flow

# Feign 使用 httpclient 连接池
feign:
#  httpclient:
#    enabled: true
#    connection-timeout: 1000
  sentinel:
    enabled: true      # 开启 Sentinel 对 Feign 的支持