spring:
  sql:
    init:
      username: jd
      password: 123456
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: jd
    password: 123456