server:
  port: 8001
spring:
  application:
    name: rabbitmq-demo
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /jd
    listener:
      simple:
        acknowledge-mode: auto

config:
  rabbitmq:
    exchange: test_exchange
    queue: test.queue
    routingKey: ack.test