server:
  port: 8001
spring:
  application:
    name: nacos-demo
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        group: NACOS_GROUP
        refresh-enabled: true