resilience4j.ratelimiter:
  instances:
    test:
      limitForPeriod: 1
      limitRefreshPeriod: 5s
      timeoutDuration: 200ms
      registerHealthIndicator: true
      eventConsumerBufferSize: 100

resilience4j.circuitbreaker:
  instances:
    test:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
#      recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate