server:
  port: 8001
spring:
  application:
    name: jz-demo-redis
  redis:
    cluster:
      nodes: 127.0.0.1:7000
      max-redirects: 3
    timeout: 6000
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
#    host: 127.0.0.1
#    port: 6379
