server:
  port: 8001
spring:
  application:
    name: jz-demo-database
  datasource:
    url: jdbc:mysql://localhost:3306/jd_test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1